// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function add(x, y) {
  return x + y | 0;
}

function subtract(x, y) {
  return x - y | 0;
}

exports.add = add;
exports.subtract = subtract;
/* No side effect */
